### ISSUE TITLE
sample-dsa.{key,pub}

### ISSUE THREAD

**Issue by lol768** [UniversityofWarwick/j2ssh-fork#1]
The sample public *and private* DSA key files in the root of the repo wouldn't be the same as is used in production for `files.warwick.ac.uk`, would they? I might well be wrong, but wouldn't this make an MiTM possible without the user being aware for anyone making use of SFTP?

---------

```
➜  /tmp ssh -v username@files.warwick.ac.uk 2>&1 | grep "Server host key"
debug1: Server host key: DSA ab:22:c1:f2:bc:b2:63:f9:de:14:58:83:13:1a:ee:37
username's password: 

➜  /tmp ping files.warwick.    
➜  /tmp ping files.warwick.ac.uk
PING files.csv.warwick.ac.uk (137.205.243.61) 56(84) bytes of data.
^C
--- files.csv.warwick.ac.uk ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

➜  /tmp ssh -v username@files.warwick.ac.uk 2>&1 | grep "Server host key"
debug1: Server host key: DSA ab:22:c1:f2:bc:b2:63:f9:de:14:58:83:13:1a:ee:37
username's password: 

➜  /tmp echo "172.28.128.3 files.warwick.ac.uk" | sudo tee -a /etc/hosts
172.28.128.3 files.warwick.ac.uk
➜  /tmp ping files.warwick.ac.uk 
PING files.warwick.ac.uk (172.28.128.3) 56(84) bytes of data.
64 bytes from files.warwick.ac.uk (172.28.128.3): icmp_seq=1 ttl=64 time=0.296 ms
^C
--- files.warwick.ac.uk ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.296/0.296/0.296/0.000 ms
➜  /tmp ssh -v username@files.warwick.ac.uk 2>&1 | grep "Server host key"
debug1: Server host key: DSA ab:22:c1:f2:bc:b2:63:f9:de:14:58:83:13:1a:ee:37
username@files.warwick.ac.uk's password: 

➜  /tmp 

```

**Comment by matmannion** [comment]
Hi Adam,

You're quite right, this was an oversight when the Files.Warwick SFTP server was initially created. We've now changed the keys in use by the SFTP service.

Mat

**Comment by halfninja** [comment]
I'm aware that we don't have a formal responsible disclosure policy yet but if you could report any future suspected security issues by email to begin with, that'd be greatly appreciated Adam. I promise we wouldn't be any slower to fix it! Anyway, thanks for the heads up.

**Comment by lol768** [comment]
Thanks both.

Apologies @halfninja - I'll keep that in mind going forward. Is the helpdesk the best way to raise these sort of issues? They don't usually seem serious enough to report via CSIIRT's email (and that just seems like an additional hurdle to get the reports to those that can fix them) and I'm conscious there's work involved to triage issues that *are* reported via the helpdesk, copy the details over to JIRA etc. Does the system that handles the `webteam@` address auto-categorise the service calls it creates?

Admittedly both of those approaches are a lot better than full disclosure without warning, which in hindsight really wasn't the best idea. I do think there is some value in making it clear the public key in question shouldn't be trusted in the absence of an X509 & CRL/OCSP style system and Google should at least now index the fingerprint of the old key, but I'm sure there were better ways of achieving this.

Regards,

Adam

**Comment by halfninja** [comment]
Helpdesk is generally the best route. `webteam` will go through the same system, just auto-categorised to us.

Cheers
Nick
